export const dashcards = [
  {
    name: "Completed",
    boards: ["Program Specialist"],
    list: ["Completed (Program Specialist)"],
    status: "",
    completed: "",
  },
  {
    name: "Draft Auths",
    boards: ["Program Specialist"],
    list: ["Completed"],
    status: "",
    completed: "",
    typeOfRequest: "Draft Change",
  },
  {
    name: "New Request",
    boards: ["Program Specialist"],
    list: ["New Request"],
    status: "",
    completed: "",
  },
  {
    name: "Assigned New Request",
    boards: ["Program Specialist"],
    list: ["Assigned New Request"],
    status: "",
    completed: "",
  },
  {
    name: "Working",
    boards: ["Program Specialist"],
    list: ["Working"],
    status: "",
    completed: "",
  },
  {
    name: "Stale",
    boards: ["Program Specialist"],
    list: ["Stale"],
    status: "",
    completed: "",
  },
  {
    name: "Email Out Unscheduled",
    boards: ["PS Intro Call"],
    list: [
      "Email Out to Client (check to see if scheduled on calendar) (Create Due date for X amount of days for FU)",
    ],
    status: "",
    completed: "",
  },
  {
    name: "Total Unscheduled",
    boards: ["PS Intro Call"],
    list: [
      "Email Out to Client (check to see if scheduled on calendar) (Create Due date for X amount of days for FU)",
      "New Request (Link to Note Tag)",
    ],
    status: "",
    completed: "",
  },
  {
    name: "Total New Requests", // ?? Faltan las condiciones
    boards: [],
    list: [],
    status: "",
    completed: "",
  },
  {
    name: "Total Scheduled",
    boards: ["PS Intro Call"],
    list: ["Scheduled (Talk to Dez about Cal Link)"],
    status: "",
    completed: "",
  },
  {
    name: "Monthly Completed",
    boards: ["PS Intro Call"],
    list: ["Completed (Auto Archive EOM & Once completed, remove tags)"],
    status: "",
    completed: "",
  },
  {
    name: "LOOKER BOARD", // ?? Faltan las condiciones
    boards: [],
    list: [],
    status: "",
    completed: "",
  },
  {
    name: "SCORES AND FEEDBACK", // ?? Faltan las condiciones
    boards: [],
    list: [],
    status: "",
    completed: "",
  },
  {
    name: "15+ days Uncompleted",
    boards: [
      "PS Board: Celia",
      "Program Specialist",
      "PS Board: Crista",
      "PS Board: Eric",
      "PS Board: Holly",
      "PS Board: Janay",
      "PS Board: Kim",
      "PS Board: LUSA",
      "PS Board: Marina",
      "PS Board: Mia Rocello",
      "PS Board: Miriam",
      "PS Board: Nicolas",
      "PS Board: Priority",
      "PS Board: Stephanie",
      "PS Board: Zain",
    ],
    list: ["Working (Program Specialist)", "Working", "Follow up:"],
    status: "",
    completed: "",
    created: "earlier than 15 days ago",
  },
  {
    name: "30+ Days uncompleted", // ?? Faltan las condiciones
    boards: [],
    list: [],
    status: "",
    completed: "",
  },
  {
    name: "2+ Days Uncompleted",
    boards: ["Program Specialist"],
    list: ["New Request", "Working"],
    status: "",
    completed: "",
    created: "earlier than 2 days ago",
  },
  {
    name: "3+ Days Uncompleted",
    boards: ["Program Specialist"],
    list: ["New Request", "Working"],
    status: "",
    completed: "",
    created: "earlier than 3 days ago",
  },
  {
    name: "4+ Days Uncompleted",
    boards: ["Program Specialist"],
    list: ["New Request", "Working"],
    status: "",
    completed: "",
    created: "earlier than 4 days ago",
  },
  {
    name: "5+ Days Uncompleted",
    boards: ["Program Specialist"],
    list: ["New Request", "Working"],
    status: "",
    completed: "",
    created: "earlier than 5 days ago",
  },
  {
    name: "6+ Days Uncompleted",
    boards: ["Program Specialist"],
    list: ["New Request", "Working"],
    status: "",
    completed: "",
    created: "earlier than 6 days ago",
  },
  {
    name: "PS Task Volume", // ?? Faltan las condiciones
    boards: [],
    list: [],
    status: "",
    completed: "",
  },
];
