export const dashcards = [
  {
    name: "CSS Still Due",
    boards: [
      "CSS Board: Adrian",
      "CSS Board: Alexandra",
      "CSS Board: Alexis",
      "CSS Board: Brittney",
      "CSS Board: Carolyn",
      "CSS Board: David",
      "CSS Board: Don",
      "CSS Board: Eric Bluehawk",
      "CSS Board: Eric Sismaet",
      "CSS Board: Irma",
      "CSS Board: Janay",
      "CSS Board: Jill",
      "CSS Board: Karel",
      "CSS Board: Micah",
      "CSS Board: Marcella",
      "CSS Board: Rich",
      "CSS Board: Michael",
      "CSM Board: Josh",
    ],
    list: ["To Do", "Working"],
    status: "",
    completed: "",
  },
  {
    name: "CSS Done",
    boards: [
      "CSM Board: Josh",
      "CSS Board: Adrian",
      "CSS Board: Alexandra",
      "CSS Board: Alexis",
      "CSS Board: Brittney",
      "CSS Board: Carolyn",
      "CSS Board: David",
      "CSS Board: Don",
      "CSS Board: Eric Bluehawk",
      "CSS Board: Eric Sismaet",
      "CSS Board: Irma",
      "CSS Board: Janay",
      "CSS Board: Jill",
      "CSS Board: Karel",
      "CSS Board: Marcella",
      "CSS Board: Micah",
      "CSS Board: Michael",
      "CSS Board: Rich",
    ],
    list: ["Done"],
    status: "",
    completed: "",
  },
  {
    name: "Support Still Due",
    boards: ["Support"],
    list: [
      "Working- Mesh",
      "New Request",
      "Working Justine",
      "Working- Bree",
      "Working- Jonathan",
      "Working - Lina",
      "Working - Raff",
      "Working - Rose",
      "Working- Daniel",
      "Working- Nelle",
    ],
    status: "",
    completed: "",
  },
  {
    name: "Support Done",
    boards: ["Support", "Support Board: Katie PTR", "Support Board: Rose"],
    list: ["Done"],
    status: "",
    completed: "",
  },
  {
    name: "Lead Evaluations Done",
    boards: ["Lead Evaluations"],
    list: [
      "Rose Done",
      "Don Done",
      "Micah Done",
      "Eric Done",
      "David Done",
      "Josh Done",
    ],
    status: "",
    completed: "",
  },
  {
    name: "Stale Cancels",
    boards: [
      "CSS Board: Adrian",
      "CSS Board: Alexandra",
      "CSS Board: Alexis",
      "CSS Board: Brittney",
      "CSS Board: Carolyn",
      "CSS Board: Dane",
      "CSS Board: David",
      "CSS Board: Don",
      "CSS Board: Eric Bluehawk",
      "CSS Board: Eric Sismaet",
      "CSS Board: Irma",
      "CSS Board: Jill",
      "CSS Board: Janay",
      "CSS Board: Karel",
      "CSS Board: Marcella",
      "CSS Board: Micah",
      "CSS Board: Michael",
      "CSS Board: Rich",
    ],
    list: ["Done"],
    status: "Stale Cancel",
    completed: "this month",
  },
  {
    name: "Call Back",
    boards: [
      "CSM Board: Josh",
      "CSS Board: Adrian",
      "CSS Board: Alexandra",
      "CSS Board: Alexis",
      "CSS Board: Brittney",
      "CSS Board: Carolyn",
      "CSS Board: Dane",
      "CSS Board: David",
      "CSS Board: Don",
      "CSS Board: Eric Bluehawk",
      "CSS Board: Eric Sismaet",
      "CSS Board: Irma",
      "CSS Board: Janay",
      "CSS Board: Jill",
      "CSS Board: Karel",
      "CSS Board: Marcella",
      "CSS Board: Micah",
      "CSS Board: Michael",
      "CSS Board: Rich",
    ],
    list: ["Done"],
    status: "Call Back",
    completed: "this month",
  },
  {
    name: "Follow up",
    boards: [
      "CSS Board: Adrian",
      "CSS Board: Alexandra",
      "CSS Board: Alexis",
      "CSS Board: Brittney",
      "CSS Board: Carolyn",
      "CSS Board: David",
      "CSS Board: Don",
      "CSS Board: Eric Bluehawk",
      "CSS Board: Eric Sismaet",
      "CSS Board: Irma",
      "CSS Board: Janay",
      "CSS Board: Karel",
      "CSS Board: Marcella",
      "CSS Board: Jill",
      "CSS Board: Michael",
      "CSS Board: Micah",
      "CSS Board: Rich",
    ],
    list: ["Done"],
    status: "Follow up",
    completed: "this month",
  },
  {
    name: "Bank Changes",
    boards: [
      "CSS Board: Adrian",
      "CSS Board: Alexandra",
      "CSS Board: Alexis",
      "CSS Board: Brittney",
      "CSS Board: Carolyn",
      "CSS Board: Dane",
      "CSS Board: David",
      "CSS Board: Don",
      "CSS Board: Eric Bluehawk",
      "CSS Board: Eric Sismaet",
      "CSS Board: Irma",
      "CSS Board: Janay",
      "CSS Board: Jill",
      "CSS Board: Karel",
      "CSS Board: Marcella",
      "CSS Board: Michael",
      "CSS Board: Micah",
      "CSS Board: Rich",
      "Support",
      "Support Board: Jonathan",
      "Support Board: Bree",
      "Support Board: Daniel",
      "Support Board: Juan",
      "Support Board: Justine",
      "Support Board: Katie PTR",
      "Support Board: Lina",
      "Support Board: Mesh",
      "Support Board: Nelle",
      "Support Board: Raff",
      "Support Board: Rose",
    ],
    list: ["Done"],
    status: "Bank Change",
    completed: "this month",
  },
  {
    name: "Draft Changes",
    boards: [
      "CSS Board: Adrian",
      "CSS Board: Alexandra",
      "CSS Board: Alexis",
      "CSS Board: Brittney",
      "CSS Board: Carolyn",
      "CSS Board: Don",
      "CSS Board: David",
      "CSS Board: Eric Bluehawk",
      "CSS Board: Eric Sismaet",
      "CSS Board: Janay",
      "CSS Board: Irma",
      "CSS Board: Jill",
      "CSS Board: Karel",
      "CSS Board: Marcella",
      "CSS Board: Micah",
      "CSS Board: Michael",
      "CSS Board: Rich",
      "Support Board: Rose",
      "Support Board: Nelle",
      "Support Board: Mesh",
      "Support Board: Lina",
      "Support Board: Katie PTR",
      "Support Board: Justine",
      "Support Board: Juan",
      "Support Board: Jonathan",
      "Support Board: Daniel",
      "Support Board: Bree",
    ],
    list: ["Done"],
    status: "Draft Change",
    completed: "this month",
  },
  {
    name: "Katie To Do PTR",
    boards: ["Support Board: Katie PTR"],
    list: ["Working", "Program Term Revisions To Do"],
    status: "",
    completed: "",
  },
  {
    name: "Done",
    boards: ["Katie"],
    list: ["Done"],
    status: "",
    completed: "",
  },
  {
    name: "PTR Done",
    boards: ["Katie", "Support Board: Katie PTR"],
    list: ["Done"],
    status: "",
    completed: "",
  },
  {
    name: "Reinstatement Done",
    boards: ["Katie"],
    list: ["Done"],
    status: "Reinstatement",
    completed: "",
  },
  {
    name: "Eric",
    boards: ["Lead Evaluations"],
    list: ["Eric Done"],
    status: "",
    completed: "this week",
  },
  {
    name: "Don",
    boards: ["Lead Evaluations"],
    list: ["Don Done"],
    status: "",
    completed: "this week",
  },
  {
    name: "Micah",
    boards: ["Lead Evaluations"],
    list: ["Micah Done"],
    status: "",
    completed: "this week",
  },
  {
    name: "David",
    boards: ["Lead Evaluations"],
    list: ["David Done"],
    status: "",
    completed: "this week",
  },
  {
    name: "Rose",
    boards: ["Lead Evaluations"],
    list: ["Rose Done"],
    status: "",
    completed: "this week",
  },
];
